extraction:
  cpp:
    prepare:
      packages: [
        build-essential,
        curl, wget, rsync, pv,
        make, gcc, g++, bc, python, xutils-dev, flex, bison, autogen, libgcrypt20-dev, libjson-c-dev,
        autopoint, pkgconf, autoconf, libtool, libcurl4-openssl-dev, libprotobuf-dev, libprotobuf-c-dev, protobuf-compiler, protobuf-c-compiler, libssl-dev,
        cmake
      ]

    after_prepare:
    - .azure-pipelines/scripts/dump_system_info.sh
    
    configure:
      command:
      - echo "no configure step"

    index:
      build_command:
      - make DEBUG=true OE_HAS_QUOTE_PROVIDER=OFF
