extraction:
  cpp:
    prepare:
      packages: [
        build-essential,
        curl, wget, rsync, pv,
        make, gcc, g++, bc, python, xutils-dev, flex, bison, autogen, libgcrypt20-dev, libjson-c-dev,
        autopoint, pkgconf, autoconf, libtool, libcurl4-openssl-dev, libprotobuf-dev, libprotobuf-c-dev, protobuf-compiler, protobuf-c-compiler, libssl-dev,
        cmake, npm
      ]

    after_prepare:
    - printenv
    # Install npm packages in HOME.
    # https://stackoverflow.com/a/13021677
    - export NPM_PACKAGES="$HOME/.npm-packages"
    - mkdir -p "$NPM_PACKAGES"
    - echo "prefix = $NPM_PACKAGES" >> ~/.npmrc
    - export PATH="$NPM_PACKAGES/bin:$PATH"
    - export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
    # esy is an Open Enclave build dependency.
    - npm install -g esy
    
    configure:
      command:
      - echo "no configure step"

    index:
      build_command:
      - make DEBUG=true OE_HAS_QUOTE_PROVIDER=OFF
