extraction:
  cpp:
    after_prepare:
    - export NOSUDO=1
    - .azure-pipelines/scripts/install_prerequisites.sh
    - .azure-pipelines/scripts/dump_system_info.sh
    
    configure:
      command:
      - echo "no configure step"
    
    before_index:
    - export build_mode=debug
    - export SGXLKL_PREFIX=dist

    index:
      build_command:
      - .azure-pipelines/scripts/build.sh
